export const selectData = [ "Administrative Assistant" , "Receptionist" , "Office Manager" , "Auditing Clerk" ,
"Bookkeeper" ,
"Account Executive" ,
"Branch Manager" ,
"Business Manager" ,
"Quality Control Coordinator" ,
"Administrative Manager" ,
"Chief Executive Officer" ,
"Business Analyst" ,
"Risk Manager" ,
"Human Resources" ,
"Office Assistant" ,
"Secretary" ,
"Office Clerk" ,
"File Clerk" ,
"Account Collector" ,
"Administrative Specialist" ,
"Executive Assistant" ,
"Program Administrator" ,
"Program Manager" ,
"Administrative Analyst" ,
"Data Entry" ,
"Computer Scientist" ,
"IT Professional" ,
"UX Designer & UI Developer" ,
"SQL Developer" ,
"Web Designer" ,
"Web Developer" ,
"Help Desk Worker/Desktop Support" ,
"Software Engineer" ,
"Data Entry" ,
"DevOps Engineer" ,
"Computer Programmer" ,
"Network Administrator" ,
"Information Security Analyst" ,
"Artificial Intelligence Engineer" ,
"Cloud Architect" ,
"IT Manager" ,
"Technical Specialist" ,
"Application Developer" ,
"Chief Technology Officer (CTO)" ,
"Chief Information Officer (CIO)" ,
"Sales Associate" ,
"Sales Representative" ,
"Sales Manager" ,
"Retail Worker" ,
"Store Manager" ,
"Sales Representative" ,
"Sales Manager" ,
"Real Estate Broker" ,
"Sales Associate" ,
"Cashier" ,
"Store Manager" ,
"Account Executive" ,
"Account Manager" ,
"Area Sales Manager" ,
"Direct Salesperson" ,
"Director of Inside Sales" ,
"Outside Sales Manager" ,
"Sales Analyst" ,
"Market Development Manager" ,
"B2B Sales Specialist" ,
"Sales Engineer" ,
"Construction Worker" ,
"Taper" ,
"Plumber" ,
"Heavy Equipment Operator" ,
"Vehicle or Equipment Cleaner" ,
"Carpenter" ,
"Electrician" ,
"Painter" ,
"Welder" ,
"Handyman" ,
"Boilermaker" ,
"Crane Operator" ,
"Building Inspector" ,
"Pipefitter" ,
"Sheet Metal Worker" ,
"Iron Worker" ,
"Mason" ,
"Roofer" ,
"Solar Photovoltaic Installer" ,
"Well Driller" ,
"Credit Authorizer" ,
"Benefits Manager" ,
"Credit Counselor" ,
"Accountant" ,
"Bookkeeper" ,
"Accounting Analyst" ,
"Accounting Director" ,
"Accounts Payable/Receivable Clerk" ,
"Auditor" ,
"Budget Analyst" ,
"Controller" ,
"Financial Analyst" ,
"Finance Manager" ,
"Economist" ,
"Payroll Manager" ,
"Payroll Clerk" ,
"Financial Planner" ,
"Financial Services Representative" ,
"Finance Director" ,
"Commercial Loan Officer"
] 